import type { Metadata } from "next";
// imports a type for the METADATA object from Next.js
// this is used to set <title> and <meta> tags , etc. statically (at build time)

import { Geist, Geist_Mono } from "next/font/google";
// we are importing Google Fonts using Next.js's build-in font optimization
// Geist and Geist_Mono are fonts from Vercel's Geist font family

import "./globals.css";

import Providers from "./providers"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
// this loads the Geist sans-serif font
// it enables font-family usage via the custom css variable --font-geist-sans
// subnets: ["latin"] ensures the correct character are loaded (smaller bundle)

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})
// something like above

export const metadata: Metadata = {
    title: "Siavash Mosadegh",
    description: "Generated by create next app",
}
// Defines static metadata for every page in your app
// this replaces the older method of using <Head> manually on every page
// values here are used to populate the HTML <head> at build time

import Navbar from "@/components/Navbar/Navbar";
import Layout from "@/components/Layout/Layout";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable}`}
                // the code above Applies our custom font variables to the <body> tag
                // you can now use font-family: var(--font-geist-sans) or --font-geist-mono in your css
            >
                <Providers>
                    <Layout children={children}/>
                    {/* <Navbar />

                    <main>{children}</main> */}
                </Providers>
            </body>
        </html>
    )
}
